model: TransUnet

exp_id: "TransUnet_dca1"
batch_size: 8
num_workers: 4

dataset: "DCA1"

lr: 0.00001
steps: []
gamma: 0.1
weight_decay: 0.05

iterations: 10000
log_text_interval: 100
log_image_interval: 1000
save_checkpoint_interval:
save_checkpoint_its: [6000, 8000, 10000]

debug: false
load_checkpoint: